// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl) on 06/17/2013 01:04:05+0200
package it.tyto.iia.web.agencysearch;

import it.tyto.iia.vo.AgencyVO;

/**
 * @see it.tyto.iia.web.agencysearch.AgencySearchController
 */
public class AgencySearchControllerImpl
    extends AgencySearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 7030673696079246842L;

    /**
     * @see it.tyto.iia.web.agencysearch.AgencySearchController#populateAgencySearch(java.lang.Integer prefix, java.lang.String name, AgencyVO[] agencies)
     */
    @Override
    public void populateAgencySearch(PopulateAgencySearchForm form)
    {
        // populating the table with a dummy list
        form.setAgencies(agencies);
    }

    /**
     * This dummy variable is used to populate the "agencies" table.
     * You may delete it when you add you own code in this controller.
     */
    private static final AgencyVO[] agencies =
        new AgencyVO[]
        {
            new AgencyVO("name-1", null, false, "organisationName-1", "details-1", "address-1", "phone1-1", "phone2-1", "fax1-1", "fax2-1", "email-1", "website-1"),
            new AgencyVO("name-2", null, false, "organisationName-2", "details-2", "address-2", "phone1-2", "phone2-2", "fax1-2", "fax2-2", "email-2", "website-2"),
            new AgencyVO("name-3", null, false, "organisationName-3", "details-3", "address-3", "phone1-3", "phone2-3", "fax1-3", "fax2-3", "email-3", "website-3"),
            new AgencyVO("name-4", null, false, "organisationName-4", "details-4", "address-4", "phone1-4", "phone2-4", "fax1-4", "fax2-4", "email-4", "website-4"),
            new AgencyVO("name-5", null, false, "organisationName-5", "details-5", "address-5", "phone1-5", "phone2-5", "fax1-5", "fax2-5", "email-5", "website-5")
        };
}