// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl) on 06/16/2013 17:49:04+0200
package it.tyto.iia.web.agencysearch;

import it.tyto.iia.vo.AgencyVO;

/**
 * @see it.tyto.iia.web.agencysearch.AgencySearchController
 */
public class AgencySearchControllerImpl
    extends AgencySearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 4605654516661556437L;

    /**
     * @see it.tyto.iia.web.agencysearch.AgencySearchController#populateAgencySearch(AgencyVO[] agencies)
     */
    @Override
    public void populateAgencySearch(PopulateAgencySearchForm form)
    {
        // populating the table with a dummy list
        form.setAgencies(agencies);
    }

    /**
     * This dummy variable is used to populate the "agencies" table.
     * You may delete it when you add you own code in this controller.
     */
    private static final AgencyVO[] agencies =
        new AgencyVO[]
        {
            new AgencyVO("name-1", null, false, "organisationName-1"),
            new AgencyVO("name-2", null, false, "organisationName-2"),
            new AgencyVO("name-3", null, false, "organisationName-3"),
            new AgencyVO("name-4", null, false, "organisationName-4"),
            new AgencyVO("name-5", null, false, "organisationName-5")
        };
}