// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl) on 06/16/2013 17:59:26+0200
package it.tyto.iia.web.agencydetail;

import it.tyto.iia.vo.AgencyDetailVO;

/**
 * @see it.tyto.iia.web.agencydetail.AgencyDetailController
 */
public class AgencyDetailControllerImpl
    extends AgencyDetailController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -2210165692851125111L;

    /**
     * @see it.tyto.iia.web.agencydetail.AgencyDetailController#populateAgencyDetail(java.lang.String name, AgencyDetailVO agency)
     */
    @Override
    public void populateAgencyDetail(PopulateAgencyDetailForm form)
    {
        // populating value with dummy instance
        AgencyDetailVO agency = new AgencyDetailVO();
        agency.setName(null);
        agency.setType(null);
        agency.setActive(false);
        agency.setOrganisationName(null);
        form.setAgency(agency);
    }

}