// Generated by: hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package it.tyto.iia.domain;

import it.tyto.iia.vo.AgencyContactVO;

/**
 * @see AgencyContact
 */
public class AgencyContactDaoImpl
    extends AgencyContactDaoBase
{
    /**
     * {@inheritDoc}
     */
    public void toAgencyContactVO(
        AgencyContact source,
        AgencyContactVO target)
    {
        // TODO verify behavior of toAgencyContactVO
        super.toAgencyContactVO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    public AgencyContactVO toAgencyContactVO(final AgencyContact entity)
    {
        // TODO verify behavior of toAgencyContactVO
        return super.toAgencyContactVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private AgencyContact loadAgencyContactFromAgencyContactVO(AgencyContactVO agencyContactVO)
    {
        // TODO implement loadAgencyContactFromAgencyContactVO
        throw new UnsupportedOperationException("it.tyto.iia.domain.loadAgencyContactFromAgencyContactVO(AgencyContactVO) not yet implemented.");

        /* A typical implementation looks like this:
        AgencyContact agencyContact = this.get(agencyContactVO.getId());
        if (agencyContact == null)
        {
            agencyContact = AgencyContact.Factory.newInstance();
        }
        return agencyContact;
        */
    }

    /**
     * {@inheritDoc}
     */
    public AgencyContact agencyContactVOToEntity(AgencyContactVO agencyContactVO)
    {
        // TODO verify behavior of agencyContactVOToEntity
        AgencyContact entity = this.loadAgencyContactFromAgencyContactVO(agencyContactVO);
        this.agencyContactVOToEntity(agencyContactVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void agencyContactVOToEntity(
        AgencyContactVO source,
        AgencyContact target,
        boolean copyIfNull)
    {
        // TODO verify behavior of agencyContactVOToEntity
        super.agencyContactVOToEntity(source, target, copyIfNull);
    }
}