// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl) on 06/17/2013 01:04:05+0200
package it.tyto.iia.web.agencydetail;

import it.tyto.iia.vo.AgencyDetailVO;
import it.tyto.iia.vo.CountryVO;

/**
 * @see it.tyto.iia.web.agencydetail.AgencyDetailController
 */
public class AgencyDetailControllerImpl
    extends AgencyDetailController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -2210165692851125111L;

    /**
     * @see it.tyto.iia.web.agencydetail.AgencyDetailController#populateAgencyDetail(java.lang.String name, AgencyDetailVO agency, CountryVO[] assignedCountries, CountryVO[] allCountries)
     */
    @Override
    public void populateAgencyDetail(PopulateAgencyDetailForm form)
    {
        // populating value with dummy instance
        AgencyDetailVO agency = new AgencyDetailVO();
        agency.setName(null);
        agency.setType(null);
        agency.setActive(false);
        agency.setOrganisationName(null);
        agency.setDetails(null);
        agency.setAddress(null);
        agency.setPhone1(null);
        agency.setPhone2(null);
        agency.setFax1(null);
        agency.setFax2(null);
        agency.setEmail(null);
        agency.setWebsite(null);
        form.setAgency(agency);
        // populating the table with a dummy list
        form.setAssignedCountries(assignedCountries);
        // populating the table with a dummy list
        form.setAllCountries(allCountries);
    }

    /**
     * This dummy variable is used to populate the "assignedCountries" table.
     * You may delete it when you add you own code in this controller.
     */
    private static final CountryVO[] assignedCountries =
        new CountryVO[]
        {
            new CountryVO("code-1", "name-1"),
            new CountryVO("code-2", "name-2"),
            new CountryVO("code-3", "name-3"),
            new CountryVO("code-4", "name-4"),
            new CountryVO("code-5", "name-5")
        };
    /**
     * This dummy variable is used to populate the "allCountries" table.
     * You may delete it when you add you own code in this controller.
     */
    private static final CountryVO[] allCountries =
        new CountryVO[]
        {
            new CountryVO("code-1", "name-1"),
            new CountryVO("code-2", "name-2"),
            new CountryVO("code-3", "name-3"),
            new CountryVO("code-4", "name-4"),
            new CountryVO("code-5", "name-5")
        };
}