// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl) on 06/16/2013 17:49:04+0200
package it.tyto.iia.web.home;

/**
 * @see it.tyto.iia.web.home.HomeController
 */
public class HomeControllerImpl
    extends HomeController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 477390477626499436L;

    /**
     * @see it.tyto.iia.web.home.HomeController#populateHome()
     */
    @Override
    public void populateHome()
    {
    }

}